name: Node.js CI

on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: "Enable corepack"
        run: corepack enable
      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version-file: ".node-version"
          cache: "pnpm"

      - run: pnpm install

      - run: pnpm run lint
      - run: pnpm run fmt --check
      - run: pnpm -r run typecheck
      - run: pnpm -r test
