name: Node.js CI

on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: "Enable corepack"
        run: corepack enable
      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version-file: ".node-version"
          cache: "pnpm"

      - name: "Install packages"
        run: pnpm install

      - name: "Run eslint"
        run: pnpm run lint
      - name: "Check prettier"
        run: pnpm run fmt --check

      - name: "Building all packages"
        run: pnpm -r build
      - name: "Typescript typecheck"
        run: pnpm -r run typecheck
      - name: "Run unit tests"
        run: pnpm -r test

      - name: "Check attw for @tvq/client"
        working-directory: packages/client
        run: |
          pnpm exec attw $(pnpm pack)

      - name: "Check attw for @tvq/h3-adapter"
        working-directory: packages/h3-adapter
        run: |
          pnpm exec attw $(pnpm pack)
